# Generated by Django 3.1.5 on 2021-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topusereco',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topuserenv',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topuserhealth',
            name='id',
        ),
        migrations.AlterField(
            model_name='topusereco',
            name='name',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topuserenv',
            name='name',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topuserhealth',
            name='name',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
