# Generated by Django 3.1.5 on 2021-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTwCategory',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('economic', models.IntegerField(blank=True, null=True)),
                ('environment', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'total_tw_category',
            },
        ),
    ]
