# Generated by Django 3.1.5 on 2021-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'final_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriginTwt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_screen_name', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'origin_twt',
                'managed': False,
            },
        ),
    ]
