# Generated by Django 3.1.5 on 2021-03-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0002_auto_20210313_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapcountry',
            new_name='Maps',
        ),
    ]
