# Generated by Django 3.1.5 on 2021-03-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0004_auto_20210313_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.CharField(max_length=150),
        ),
    ]
